<div class="alert alert-block alert-info">
<img src="./Imagenes/ITESO_Logo.png" style="width:500px;height:142px;" title="Logo ITESO">
<br><font face = "Times New Roman" size = "6"><b><center>Maestría en Sistemas Computacionales</center></b></font>
<br><font face = "Times New Roman" size = "5"><b><center>Programación para Análisis de Datos</center></b></font>

<b><br><font face = "Times New Roman" size = "4"><center>Unidad 4: Proceso de Obtención de Datos</center></font>
<font face = "Times New Roman" size = "4"><center>Tema 4.1: Exploración, Integración y Limpieza de Datos</center></font>
<font face = "Times New Roman" size = "4"><center>Subtema i: Uso de PandasGUI</center></font></b>
</div>

## USO DE PANDASGUI

La librería **Pandas** se ha convertido en la herramienta mas empleada para realizar el análisis exploratorio de datos en **Python**. Su versatilidad, flexibilidad y facilidad de uso la convierten en una de las mejores alternativas para los científicos de hoy en día. 

Existe una alternativa al uso de **Pandas** basada en una **Interfaz Gráfica de Usuario** (***Graphical User Interface, GUI***) conocida como **PandasGUI**, la cual ofrece capacidades para realizar gráficos y modificaciones directamente en el **DataFrame**, además de realizar operaciones al interior del mismo.

### La Librería PandasGUI
<br>
<img src="./Datos/GUI/PandasGUI_logo.png" style="width:100px;height:100px;" class="center">
<br>

Como su nombre lo indica, es una interfaz gráfica de usuario (**GUI**) para realizar el análisis de **DataFrames** de **Pandas**. Es un proyecto aún en desarrollo y por lo mismo puede verse modificado, su documentación en detalle puede ser consultada [en esta liga](https://pypi.org/project/pandasgui).

La instalación de **PandasGUI** se lleva a cabo a través de la ejecución del siguiente código desde una ventana de **Terminal** para `Windows`, `macOS` y `Linux`: 
```python
pip install pandasgui
```
A manera de ejemplo para su uso, se empleará un **DataFrame** cuyos datos están contenidos en el archivo `Titanic.csv`, para ello se leerán los datos de la manera tradicional:

In [4]:
#Importación de librerías
import pandas as pd

#Lectura de los datos desde el archivo TXT
datos_df = pd.read_csv('./Datos/GUI/Titanic.csv')

#Impresión de los Resultados
print("El DataFrame es:")
display(datos_df)

El DataFrame es:

,Unnamed: 0,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

Ahora se importará la librería **PandasGUI** por medio de la instrucción:
```python
from pandasgui import show
```
Se empeará el método `.show()` para generar la ventana **GUI** que contiene el **DataFrame**, a través de la cual se pueden realizar toda una serie de operaciones.

In [5]:
#Importación de librerías
from pandasgui import show

#GUI con el DataFrame
GUI = show(datos_df)

ModuleNotFoundError: No module named 'pandasgui'

Una vez que se ejecuta el comando, aparece una ventana emergente similar a la siguiente donde se muestra el contenido del **DataFrame** de manera interactiva: 
<br>
<img src="./Datos/GUI/PandasGUI.png" style="width:853px;height:500px;" class="center">
<br>

### Ver y Ordenar Series y DataFrames
Es posible observar el contenido total del **DataFrame** así como realizar un ordenamiento del mismo de manera ascendente o descendente a través de los valores de las columnas, simplemente dando *click* en alguno de los encabezados:
<br>
<img src="./Datos/GUI/Ordenado.png" style="width:853px;height:500px;" class="center">
<br>

### Filtrado del DataFrame con Expresiones de Consulta
Una vez explorado el contenido del **DataFrame**, es posible realizar operaciones de filtado basadas en expresiones de consulta (*query expressions*). EL método `.Dataframe.query()` de **Pandas** es empleado para este proceso, el cual toma una expresión como una cadena y realiza el filtado en el **DataFrame**, para generar un resultado con el filtro aplicado. 

La descripción detallada del método `.Dataframe.query()` de **Pandas** puede consultarse [en esta liga](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html).

A través de la **GUI** se pueden aplicar a manera de ejemplo los siguientes tres filtros:
1. Los pasajeros que son hombres (*male*).
2. Los pasajeros que pertenecen a `Pclass` número 3.
3. Los pasajeros que sobrevivieron el naufragio. 

El siguiente gráfico animado muestra el proceso que se realiza en la ventana de la **GUI** para realizar estas operaciones:
<br>
<img src="./Datos/GUI/Filtrado.gif" style="width:897px;height:500px;" class="center">
<br>

### Edición de Datos
Otra característica que ofrece esta herramienta es que es posible editar directamente cualqueira de los valores contenidos en el **DataFrame**, e incluso seleccionar valores para realizar las operaciones de *copiado* y *pegado* para utilizarlos en aplicaciones como el ***Block de Notas*** o ***Microsoft Excel***.
<br>
<img src="./Datos/GUI/Exportado.png" style="width:853px;height:500px;" class="center">
<br>

### Resumen Estadístico
La herramienta **PandasGUI** proporciona un resumen de las características estadísticas de los datos contenidos en el **DataFrame**. 

El siguiente gráfico muestra la información estadística proporcionada por la ventana de la **GUI**:
<br>
<img src="./Datos/GUI/Estadisticos.png" style="width:853px;height:500px;" class="center">
<br>

### Gráficos Interactivos
La visualización de los datos es un elemento esencial en cualquier proceso de análisis de datos. La herramienta **PandasGUI** proporciona varias opciones para realizar de manera rápida algún gráfico con los datos contenidos en el **DataFrame**.

El siguiente gráfico animado muestra el proceso interactivo que se realiza en la ventana de la **GUI** para obtener un gráfico de pastel, un gráfico de barras y una nube de palabras:
<br>
<img src="./Datos/GUI/Graficado.gif" style="width:927px;height:500px;" class="center">
<br>

### Cambio de Tamaño del DataFrame
En algunas ocasiones es necesario realizar un cambio del tamaño del **DataFrame** para poder tener una mejor visualización y comprensión de los datos que contiene. 

La herramienta **PandasGUI** contiene dos funciones, `Pivot` y `Melt`, las cuales son de gran ayuda en este proceso.

El siguiente gráfico animado muestra el proceso que se realiza en la ventana de la **GUI** para realizar una tabla pivote por medio de la función `Pivot`:
<br>
<img src="./Datos/GUI/Modificado.gif" style="width:893px;height:500px;" class="center">
<br>

### Importar Archivos CSV
Otra propiedad interesante proporcionada por la herramienta **PandasGUI** es la importación de un nuevo **DataFrame** dentro de uno ya existente, para ello simplemente se realiza una operación de *arrastre* a la ventana de la **GUI**.

El siguiente gráfico animado muestra el proceso que se realiza en la ventana de la **GUI** para importar un nuevo archivo con formato `CSV`:
<br>
<img src="./Datos/GUI/Importacion.gif" style="width:1097px;height:500px;" class="center">
<br>

<br>
<img src="./Imagenes/Pandas.png" style="width:1024px;height:500px;" class="center">
<br>

<div class="alert alert-block alert-danger">
<b>.: Fin del Tema :.</b>
</div>